//---------------------------------------------------------------------------//
//!
//! \file   MonteCarlo_StandardDependentPhaseSpaceDimensionDistribution.hpp
//! \author Alex Robinson
//! \brief  Standard dependent phase space dimension distribution class decl.
//!
//---------------------------------------------------------------------------//

#ifndef MONTE_CARLO_STANDARD_DEPENDENT_PHASE_SPACE_DIMENSION_DISTRIBUTION_HPP
#define MONTE_CARLO_STANDARD_DEPENDENT_PHASE_SPACE_DIMENSION_DISTRIBUTION_HPP

// FRENSIE Includes
#include "MonteCarlo_DependentPhaseSpaceDimensionDistribution.hpp"
#include "Utility_TwoDDistribution.hpp"
#include "Utility_PartiallyTabularTwoDDistribution.hpp"
#include "Utility_FullyTabularTwoDDistribution.hpp"
#include "Utility_ExplicitTemplateInstantiationMacros.hpp"

namespace MonteCarlo{

//! The standard dependent phase space dimension distribution class
template<PhaseSpaceDimension parent_dimension,
         PhaseSpaceDimension dimension,
         typename TwoDDistributionBaseType>
class StandardDependentPhaseSpaceDimensionDistribution : public DependentPhaseSpaceDimensionDistribution<parent_dimension,dimension>
{

public:

  //! Constructor
  StandardDependentPhaseSpaceDimensionDistribution(
                         const std::shared_ptr<const TwoDDistributionBaseType>&
                         dimension_distribution );

  //! Destructor
  virtual ~StandardDependentPhaseSpaceDimensionDistribution()
  { /* ... */ }

  //! Check if the dimension distribution is continuous
  bool isContinuous() const override;

  //! Check if the dimension distribution is tabular
  bool isTabular() const override;

  //! Check if the dimension distribution is uniform (somewhere)
  bool isUniform() const;

  //! Check if the underlying distribution has the form of interest
  bool hasForm(
        const Utility::OneDDistributionType distribution_type ) const override;

  //! Get the distribution type name
  std::string getDistributionTypeName() const override;

  //! Evaluate the dimension distribution without cascade to dependent dists.
  double evaluateWithoutCascade(
                     const PhaseSpacePoint& phase_space_point ) const override;

  //! Sample a dimension value without a cascade to the dependent dists.
  virtual void sampleWithoutCascade(
                          PhaseSpacePoint& phase_space_sample ) const override;

  //! Sample a dimension value without a cascade to the dependent dists.
  virtual void sampleAndRecordTrialsWithoutCascade(
                        PhaseSpacePoint& phase_space_sample,
                        ModuleTraits::InternalCounter& trials ) const override;

  //! Set the dimension value (weight appropriately)
  void setDimensionValueAndApplyWeight(
                                 PhaseSpacePoint& phase_space_sample,
                                 const double dimension_value ) const override;

protected:

  //! Evaluate the PDF of this dimension distribution
  double evaluatePDFWithoutCascade( const double parent_dimension_value,
                                    const double dimension_value ) const;
  
private:

  // The dimension distribution
  std::shared_ptr<const TwoDDistributionBaseType> d_dimension_distribution;
};

// Explicit instantiation (extern declaration)
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,ENERGY_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TIME_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION,Utility::TwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,ENERGY_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TIME_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION,Utility::TwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,ENERGY_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,TIME_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION,Utility::TwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION,Utility::TwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION,Utility::TwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION,Utility::TwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TIME_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,WEIGHT_DIMENSION,Utility::TwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,ENERGY_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,WEIGHT_DIMENSION,Utility::TwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,ENERGY_DIMENSION,Utility::TwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TIME_DIMENSION,Utility::TwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,ENERGY_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TIME_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,ENERGY_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TIME_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,ENERGY_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,TIME_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TIME_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,WEIGHT_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,ENERGY_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,WEIGHT_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,ENERGY_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TIME_DIMENSION,Utility::PartiallyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,ENERGY_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TIME_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION,Utility::FullyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,ENERGY_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TIME_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION,Utility::FullyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,ENERGY_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,TIME_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION,Utility::FullyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION,Utility::FullyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION,Utility::FullyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION,Utility::FullyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TIME_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,WEIGHT_DIMENSION,Utility::FullyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,ENERGY_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,WEIGHT_DIMENSION,Utility::FullyTabularTwoDDistribution> );

EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,PRIMARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,SECONDARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TERTIARY_SPATIAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,ENERGY_DIMENSION,Utility::FullyTabularTwoDDistribution> );
EXTERN_EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TIME_DIMENSION,Utility::FullyTabularTwoDDistribution> );
  
} // end MonteCarlo namespace

//---------------------------------------------------------------------------//
// Template Includes.
//---------------------------------------------------------------------------//

#include "MonteCarlo_StandardDependentPhaseSpaceDimensionDistribution_def.hpp"

//---------------------------------------------------------------------------//

#endif // end MONTE_CARLO_STANDARD_DEPENDENT_PHASE_SPACE_DIMENSION_DISTRIBUTION_HPP

//---------------------------------------------------------------------------//
// end MonteCarlo_StandardDependentPhaseSpaceDimensionDistribution.hpp
//---------------------------------------------------------------------------//
