//---------------------------------------------------------------------------//
//!
//! \file   MonteCarlo_DependentPhaseSpaceDimensionDistribution.cpp
//! \author Alex Robinson
//! \brief  Dependent phase space dimension distribution class template
//!         instantiations
//!
//---------------------------------------------------------------------------//

// FRENSIE Includes
#include "MonteCarlo_DependentPhaseSpaceDimensionDistribution.hpp"

namespace MonteCarlo{

// Explicit instantiation
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,ENERGY_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,TIME_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION> );

EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,ENERGY_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,TIME_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION> );

EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,ENERGY_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,TIME_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_SPATIAL_DIMENSION,WEIGHT_DIMENSION> );

EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<PRIMARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION> );

EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<SECONDARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION> );

EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,PRIMARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,SECONDARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,TERTIARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,ENERGY_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,TIME_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TERTIARY_DIRECTIONAL_DIMENSION,WEIGHT_DIMENSION> );

EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,PRIMARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,SECONDARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TERTIARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,TIME_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<ENERGY_DIMENSION,WEIGHT_DIMENSION> );

EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,PRIMARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,SECONDARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,TERTIARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,ENERGY_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<TIME_DIMENSION,WEIGHT_DIMENSION> );

EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,PRIMARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,SECONDARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TERTIARY_SPATIAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,PRIMARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,SECONDARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TERTIARY_DIRECTIONAL_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,ENERGY_DIMENSION> );
EXPLICIT_TEMPLATE_CLASS_INST( DependentPhaseSpaceDimensionDistribution<WEIGHT_DIMENSION,TIME_DIMENSION> );
  
} // end MonteCarlo namespace

//---------------------------------------------------------------------------//
// end MonteCarlo_DependentPhaseSpaceDimensionDistribution.cpp
//---------------------------------------------------------------------------//
