//---------------------------------------------------------------------------//
//!
//! \file   MonteCarlo_PhotoatomicReactionType.hpp
//! \author Alex Robinson
//! \brief  Photoatomic reaction type enumeration and helper function decls.
//!
//---------------------------------------------------------------------------//

#ifndef MONTE_CARLO_PHOTOATOMIC_REACTION_TYPE_HPP
#define MONTE_CARLO_PHOTOATOMIC_REACTION_TYPE_HPP

// Std Lib Includes
#include <string>
#include <iostream>

// FRENSIE Includes
#include "Data_SubshellType.hpp"

namespace MonteCarlo{
  
//! The photoatomic reaction type enum.
enum PhotoatomicReactionType{
  TOTAL_PHOTOATOMIC_REACTION = 1,
  TOTAL_ABSORPTION_PHOTOATOMIC_REACTION = 2,
  TOTAL_INCOHERENT_PHOTOATOMIC_REACTION = 3,
  K_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 4,
  L1_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 5,
  L2_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 6,
  L3_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 7,
  M1_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 8,
  M2_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 9,
  M3_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 10,
  M4_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 11,
  M5_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 12,
  N1_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 13,
  N2_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 14,
  N3_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 15,
  N4_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 16,
  N5_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 17,
  N6_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 18,
  N7_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 19,
  O1_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 20,
  O2_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 21,
  O3_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 22,
  O4_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 23,
  O5_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 24,
  O6_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 25,
  O7_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 26,
  O8_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 27,
  O9_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 28,
  P1_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 29,
  P2_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 30,
  P3_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 31,
  P4_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 32,
  P5_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 33,
  P6_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 34,
  P7_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 35,
  P8_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 36,
  P9_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 37,
  P10_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 38,
  P11_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 39,
  Q1_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 40,
  Q2_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 41,
  Q3_SUBSHELL_INCOHERENT_PHOTOATOMIC_REACTION = 42,
  COHERENT_PHOTOATOMIC_REACTION = 43,
  PAIR_PRODUCTION_PHOTOATOMIC_REACTION = 44,
  TRIPLET_PRODUCTION_PHOTOATOMIC_REACTION = 45,
  TOTAL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 46,
  K_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 47,
  L1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 48,
  L2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 49,
  L3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 50,
  M1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 51,
  M2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 52,
  M3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 53,
  M4_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 54,
  M5_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 55,
  N1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 56,
  N2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 57,
  N3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 58,
  N4_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 59,
  N5_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 60,
  N6_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 61,
  N7_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 62,
  O1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 63,
  O2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 64,
  O3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 65,
  O4_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 66,
  O5_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 67,
  O6_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 68,
  O7_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 69,
  O8_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 70,
  O9_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 71,
  P1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 72,
  P2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 73,
  P3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 74,
  P4_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 75,
  P5_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 76,
  P6_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 77,
  P7_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 78,
  P8_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 79,
  P9_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 80,
  P10_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 81,
  P11_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 82,
  Q1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 83,
  Q2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 84,
  Q3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 85,
  HEATING_PHOTOATOMIC_REACTION = 86
};

//! Convert a PhotoatomicReactionType enum to a string
std::string convertPhotoatomicReactionEnumToString( 
				      const PhotoatomicReactionType reaction );

//! Convert a Data::SubshellType enum to a Photoelectric PhotoatomicReactionType enum
PhotoatomicReactionType 
convertSubshellEnumToPhotoelectricPhotoatomicReactionEnum(
						 const Data::SubshellType subshell );

//! Convert a Data::SubshellType enum to a Incoherent PhotoatomicReactionType enum
PhotoatomicReactionType
convertSubshellEnumToIncoherentPhotoatomicReactionEnum(
						 const Data::SubshellType subshell );

//! Stream operator for printing PhotoatomicReactionType enums
inline std::ostream& operator<<( std::ostream& os,
				 const PhotoatomicReactionType reaction )
{
  os << convertPhotoatomicReactionEnumToString( reaction );
  return os;
}

} // end MonteCarlo namespace

#endif // end MONTE_CARLO_PHOTOATOMIC_REACTION_TYPE_HPP

//---------------------------------------------------------------------------//
// end MonteCarlo_PhotoatomicReactionType.hpp
//---------------------------------------------------------------------------//

