//---------------------------------------------------------------------------//
//!
//! \file   MonteCarlo_AdjointElectroatomicReactionType.hpp
//! \author Luke Kersting
//! \brief  Adjoint electroatomic reaction type enumeration and helper function decls.
//!
//---------------------------------------------------------------------------//

#ifndef MONTE_CARLO_ADJOINT_ELECTROATOMIC_REACTION_TYPE_HPP
#define MONTE_CARLO_ADJOINT_ELECTROATOMIC_REACTION_TYPE_HPP

// Std Lib Includes
#include <string>
#include <iostream>

// FRENSIE Includes
#include "Data_SubshellType.hpp"

namespace MonteCarlo{

//! The electroatomic reaction type enum.
enum AdjointElectroatomicReactionType{
  TOTAL_ADJOINT_ELECTROATOMIC_REACTION = 1,
  BREMSSTRAHLUNG_ADJOINT_ELECTROATOMIC_REACTION = 2,
  POSITRON_ANNIHILATION_ADJOINT_ELECTROATOMIC_REACTION = 3,
  ANALOG_ELASTIC_ADJOINT_ELECTROATOMIC_REACTION = 4,
  HYBRID_ELASTIC_ADJOINT_ELECTROATOMIC_REACTION = 5,
  CUTOFF_ELASTIC_ADJOINT_ELECTROATOMIC_REACTION = 6,
  SCREENED_RUTHERFORD_ELASTIC_ADJOINT_ELECTROATOMIC_REACTION = 7,
  MOMENT_PRESERVING_ELASTIC_ADJOINT_ELECTROATOMIC_REACTION = 8,
  ATOMIC_EXCITATION_ADJOINT_ELECTROATOMIC_REACTION = 9,
  TOTAL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 10,
  K_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 11,
  L1_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 12,
  L2_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 13,
  L3_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 14,
  M1_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 15,
  M2_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 16,
  M3_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 17,
  M4_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 18,
  M5_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 19,
  N1_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 20,
  N2_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 21,
  N3_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 22,
  N4_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 23,
  N5_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 24,
  N6_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 25,
  N7_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 26,
  O1_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 27,
  O2_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 28,
  O3_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 29,
  O4_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 30,
  O5_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 31,
  O6_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 32,
  O7_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 33,
  O8_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 34,
  O9_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 35,
  P1_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 36,
  P2_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 37,
  P3_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 38,
  P4_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 39,
  P5_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 40,
  P6_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 41,
  P7_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 42,
  P8_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 43,
  P9_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 44,
  P10_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 45,
  P11_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 46,
  Q1_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 47,
  Q2_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 48,
  Q3_SUBSHELL_ELECTROIONIZATION_ADJOINT_ELECTROATOMIC_REACTION = 49
};

//! Convert a AdjointElectroatomicReactionType enum to a string
std::string convertAdjointElectroatomicReactionEnumToString(
                              const AdjointElectroatomicReactionType reaction );

//! Convert a Data::SubshellType enum to a AdjointElectroatomicReactionType enum
AdjointElectroatomicReactionType
convertSubshellEnumToElectroionizationAdjointElectroatomicReactionEnum(
                                            const Data::SubshellType subshell );

//! Stream operator for printing AdjointElectroatomicReactionType enums
inline std::ostream& operator<<( std::ostream& os,
                               const AdjointElectroatomicReactionType reaction )
{
  os << convertAdjointElectroatomicReactionEnumToString( reaction );
  return os;
}

} // end MonteCarlo namespace

#endif // end MONTE_CARLO_ADJOINT_ELECTROATOMIC_REACTION_TYPE_HPP

//---------------------------------------------------------------------------//
// end MonteCarlo_AdjointElectroatomicReactionType.hpp
//---------------------------------------------------------------------------//


