//---------------------------------------------------------------------------//
//!
//! \file   MonteCarlo_PhotoatomicReactionType.hpp
//! \author Alex Robinson
//! \brief  Photoatomic reaction type enumeration and helper function decls.
//!
//---------------------------------------------------------------------------//

#ifndef MONTE_CARLO_PHOTOATOMIC_REACTION_TYPE_HPP
#define MONTE_CARLO_PHOTOATOMIC_REACTION_TYPE_HPP

// Std Lib Includes
#include <string>
#include <iostream>

// FRENSIE Includes
#include "MonteCarlo_SubshellType.hpp"

namespace MonteCarlo{
  
//! The photoatomic reaction type enum.
enum PhotoatomicReactionType{
  TOTAL_PHOTOATOMIC_REACTION = 1,
  INCOHERENT_PHOTOATOMIC_REACTION = 2,
  COHERENT_PHOTOATOMIC_REACTION = 3,
  PAIR_PRODUCTION_PHOTOATOMIC_REACTION = 4,
  TRIPLET_PRODUCTION_PHOTOATOMIC_REACTION = 5,
  TOTAL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 6,
  K_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 7,
  L1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 8,
  L2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 9,
  L3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 10,
  M1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 11,
  M2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 12,
  M3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 13,
  M4_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 14,
  M5_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 15,
  N1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 16,
  N2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 17,
  N3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 18,
  N4_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 19,
  N5_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 20,
  N6_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 21,
  N7_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 22,
  O1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 23,
  O2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 24,
  O3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 25,
  O4_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 26,
  O5_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 27,
  O6_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 28,
  O7_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 29,
  O8_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 30,
  O9_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 31,
  P1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 32,
  P2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 33,
  P3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 34,
  P4_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 35,
  P5_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 36,
  P6_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 37,
  P7_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 38,
  P8_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 39,
  P9_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 40,
  P10_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 41,
  P11_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 42,
  Q1_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 43,
  Q2_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 44,
  Q3_SUBSHELL_PHOTOELECTRIC_PHOTOATOMIC_REACTION = 45,
};

//! Convert a PhotoatomicReactionType enum to a string
std::string convertPhotoatomicReactionEnumToString( 
				      const PhotoatomicReactionType reaction );

//! Convert a SubshellType enum to a PhotoatomicReactionType enum
PhotoatomicReactionType convertSubshellEnumToPhotoatomicReactionEnum(
						 const SubshellType subshell );

//! Stream operator for printing PhotoatomicReactionType enums
inline std::ostream& operator<<( std::ostream& os,
				 const PhotoatomicReactionType reaction )
{
  os << convertPhotoatomicReactionEnumToString( reaction );
  return os;
}

} // end MonteCarlo namespace

#endif // end MONTE_CARLO_PHOTOATOMIC_REACTION_TYPE_HPP

//---------------------------------------------------------------------------//
// end MonteCarlo_PhotoatomicReactionType.hpp
//---------------------------------------------------------------------------//

