//---------------------------------------------------------------------------//
//!
//! \file   MonteCarlo_ElectroatomicReactionType.hpp
//! \author Luke Kersting
//! \brief  Electroatomic reaction type enumeration and helper function decls.
//!
//---------------------------------------------------------------------------//

#ifndef MONTE_CARLO_ELECTROATOMIC_REACTION_TYPE_HPP
#define MONTE_CARLO_ELECTROATOMIC_REACTION_TYPE_HPP

// Std Lib Includes
#include <string>
#include <iostream>

// FRENSIE Includes
#include "MonteCarlo_SubshellType.hpp"

namespace MonteCarlo{
  
//! The photoatomic reaction type enum.
enum ElectroatomicReactionType{
  TOTAL_ELECTROATOMIC_REACTION = 1,
  BREMSSTRAHLUNG_ELECTROATOMIC_REACTION = 2,
  POSITRON_ANNIHILATION_ELECTROATOMIC_REACTION = 3,
  ELASTIC_ELECTROATOMIC_REACTION = 4,
  INELASTIC_ELECTROATOMIC_REACTION = 5,
  ATOMIC_EXCITATION_ELECTROATOMIC_REACTION = 6,
  TOTAL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 7,
  K_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 8,
  L1_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 9,
  L2_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 10,
  L3_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 11,
  M1_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 12,
  M2_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 13,
  M3_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 14,
  M4_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 15,
  M5_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 16,
  N1_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 17,
  N2_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 18,
  N3_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 19,
  N4_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 20,
  N5_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 21,
  N6_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 22,
  N7_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 23,
  O1_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 24,
  O2_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 25,
  O3_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 26,
  O4_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 27,
  O5_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 28,
  O6_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 29,
  O7_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 30,
  O8_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 31,
  O9_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 32,
  P1_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 33,
  P2_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 34,
  P3_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 35,
  P4_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 36,
  P5_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 37,
  P6_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 38,
  P7_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 39,
  P8_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 40,
  P9_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 41,
  P10_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 42,
  P11_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 43,
  Q1_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 44,
  Q2_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 45,
  Q3_SUBSHELL_ELECTROIONIZATION_ELECTROATOMIC_REACTION = 46
};

//! Convert a ElectroatomicReactionType enum to a string
std::string convertElectroatomicReactionEnumToString( 
				      const ElectroatomicReactionType reaction );

//! Convert a SubshellType enum to a ElectroatomicReactionType enum
ElectroatomicReactionType convertSubshellEnumToElectroatomicReactionEnum(
						 const SubshellType subshell );

//! Stream operator for printing ElectroatomicReactionType enums
inline std::ostream& operator<<( std::ostream& os,
				 const ElectroatomicReactionType reaction )
{
  os << convertElectroatomicReactionEnumToString( reaction );
  return os;
}

} // end MonteCarlo namespace

#endif // end MONTE_CARLO_ELECTROATOMIC_REACTION_TYPE_HPP

//---------------------------------------------------------------------------//
// end MonteCarlo_ElectroatomicReactionType.hpp
//---------------------------------------------------------------------------//


