#!/bin/bash
##---------------------------------------------------------------------------##
## CONFIGURE FACEMC with CMAKE
##---------------------------------------------------------------------------##

EXTRA_ARGS=$@
TRILINOS_PREFIX_PATH=
TRILINOS_SOURCE_PATH=
HDF5_PREFIX_PATH=
MOAB_PREFIX_PATH=
MOAB_SOURCE_PATH=
BOOST_PREFIX_PATH=
MPI_PREFIX_PATH=
ROOT_PREFIX_PATH=
DOXYGEN_PREFIX_PATH=
FRENSIE_SRC=
FRENSIE_INSTALL=
MCNP_DATA_PATH=

# Get system details for dashboard
DISTRO="$(lsb_release -i -s)"
VERSION="$(lsb_release -r -s)"
DISTRO_VERSION=${DISTRO}-${VERSION}

source ~/.bashrc

cmake --version

cmake \
    -D CMAKE_INSTALL_PREFIX:PATH=$FRENSIE_INSTALL \
    -D CMAKE_BUILD_TYPE:STRING=RELEASE \
    -D CMAKE_VERBOSE_CONFIGURE:BOOL=OFF \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -D FRENSIE_ENABLE_DBC:BOOL=ON \
    -D FRENSIE_ENABLE_OPENMP:BOOL=ON \
    -D FRENSIE_ENABLE_MPI:BOOL=ON \
    -D FRENSIE_ENABLE_DAGMC:BOOL=ON \
    -D FRENSIE_ENABLE_ROOT:BOOL=ON \
    -D FRENSIE_ENABLE_PROFILING:BOOL=OFF \
    -D FRENSIE_ENABLE_COVERAGE:BOOL=OFF \
    -D TRILINOS_PREFIX:PATH=$TRILINOS_PREFIX_PATH \
    -D TRILINOS_SOURCE:PATH=$TRILINOS_SOURCE_PATH \
    -D ROOT_PREFIX:PATH=$ROOT_PREFIX_PATH \
    -D MOAB_PREFIX:PATH=$MOAB_PREFIX_PATH \
    -D MOAB_SOURCE:PATH=$MOAB_SOURCE_PATH \
    -D HDF5_PREFIX:PATH=$HDF5_PREFIX_PATH \
    -D BOOST_PREFIX:PATH=$BOOST_PREFIX_PATH \
    -D MPI_PREFIX:PATH=$MPI_PREFIX_PATH \
    -D ROOT_PREFIX:PATH=$ROOT_PREFIX_PATH \
    -D DOXYGEN_PREFIX:PATH=$DOXYGEN_PREFIX_PATH \
    -D MCNP_DATA_DIR:PATH=$MCNP_DATA_PATH \
    -D SETUP_DASHBOARD_CLIENT:BOOL=OFF \
    -D BUILDNAME_PREFIX:STRING=$DISTRO_VERSION \
    $EXTRA_ARGS \
    $FRENSIE_SRC

 
