#!/bin/bash

EXTRA_ARGS=$@

LAPACK_DIR=$HOME/lapack-path

source $HOME/.bashrc

cmake --version

cmake \
-D CMAKE_INSTALL_PREFIX:PATH=$LAPACK_DIR \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=ON  \
-D BUILD_SHARED_LIBS=ON \
-D BUILD_TESTING:BOOL=ON \
$EXTRA_ARGS \
$LAPACK_DIR/src