#!/bin/bash

EXTRA_ARGS=$@

LAPACK_INSTALL=$(pwd)/../../../install/lapack
LAPACK_SRC=$(pwd)/../src

source $HOME/.bashrc

cmake --version

cmake \
-D CMAKE_INSTALL_PREFIX:PATH=$LAPACK_INSTALL \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=ON  \
-D BUILD_SHARED_LIBS=ON \
-D BUILD_TESTING:BOOL=ON \
$EXTRA_ARGS \
$LAPACK_SRC
