#!/bin/bash

EXTRA_ARGS=$@
ROOT_SRC=
ROOT_INSTALL=

cmake --version

cmake \
    -D CMAKE_INSTALL_PREFIX:PATH=$ROOT_INSTALL \
    -D CMAKE_BUILD_TYPE:STRING=RELEASE \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -D CMAKE_CXX_FLAGS:STRING="-D_GLIBCXX_USE_CXX11_ABI=0" \
    $EXTRA_ARGS \
    $ROOT_SRC

