# Include all of the macros that you've defined here
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/EnforceOutOfSourceBuild.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/EnableMPISupport.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/EnableSWIGSupport.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/EnableOpenMPSupport.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/EnableMoabSupport.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/EnableDagMCSupport.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/EnableHDF5Support.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/EnableBoostSupport.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/EnableROOTSupport.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/EnableCXXStandardSupport.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/AddUninstallTarget.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/CaptureCommandLine.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/CompareCompilers.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/ProcessRootGeom.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/ACEHelpers.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/SetupPackage.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/cmake/SetupPackageTests.cmake)
