//---------------------------------------------------------------------------//
//!
//! \file   MonteCarlo_PhotonuclearReactionType.hpp
//! \author Alex Robinson
//! \brief  Photonuclear reaction type enumeration and helper function decl.
//!
//---------------------------------------------------------------------------//

#ifndef MONTE_CARLO_PHOTONUCLEAR_REACTION_TYPE_HPP
#define MONTE_CARLO_PHOTONUCLEAR_REACTION_TYPE_HPP


// FRENSIE Includes
#include "Utility_ToStringTraits.hpp"
#include "Utility_SerializationHelpers.hpp"
#include "Utility_ExceptionTestMacros.hpp"

// FRENSIE Includes
#include "Utility_TypeTraits.hpp"

namespace MonteCarlo{

/*! The photonuclear reaction type enum.
 * \details Converting the enumeration value to an integer will recover the
 * corresponding MT #.
 */
enum PhotonuclearReactionType{
  GAMMA__TOTAL_REACTION = 1,
  GAMMA__GAMMA_ELASTIC_REACTION = 2,
  GAMMA__GAMMA_NON_ELASTIC_REACTION = 3, // sum of 4,16,17,22-37,41,42,44,45,152-154,156-181,183-190,194-196,198-200
  GAMMA__N_REACTION = 4, // sum of 50-91
  GAMMA__ANYTHING_REACTION = 5,
  GAMMA__2N_D_REACTION = 11,
  GAMMA__2N_REACTION = 16,
  GAMMA__3N_REACTION = 17,
  GAMMA__TOTAL_FISSION_REACTION = 18,
  GAMMA__N_ALPHA_REACTION = 22,
  GAMMA__N_3ALPHA_REACTION = 23,
  GAMMA__2N_ALPHA_REACTION = 24,
  GAMMA__3N_ALPHA_REACTION = 25,
  GAMMA__N_P_REACTION = 28,
  GAMMA__N_2ALPHA_REACTION = 29,
  GAMMA__2N_2ALPHA_REACTION = 30,
  GAMMA__N_D_REACTION = 32,
  GAMMA__N_T_REACTION = 33,
  GAMMA__N_HE3_REACTION = 34,
  GAMMA__N_D_2ALPHA_REACTION = 35,
  GAMMA__N_T_2ALPHA_REACTION = 36,
  GAMMA__4N_REACTION = 37,
  GAMMA__2N_P_REACTION = 41,
  GAMMA__3N_P_REACTION = 42,
  GAMMA__N_2P_REACTION = 44,
  GAMMA__N_P_ALPHA_REACTION = 45,
  GAMMA__N_EXCITED_STATE_0_REACTION = 50,
  GAMMA__N_EXCITED_STATE_1_REACTION = 51,
  GAMMA__N_EXCITED_STATE_2_REACTION = 52,
  GAMMA__N_EXCITED_STATE_3_REACTION = 53,
  GAMMA__N_EXCITED_STATE_4_REACTION = 54,
  GAMMA__N_EXCITED_STATE_5_REACTION = 55,
  GAMMA__N_EXCITED_STATE_6_REACTION = 56,
  GAMMA__N_EXCITED_STATE_7_REACTION = 57,
  GAMMA__N_EXCITED_STATE_8_REACTION = 58,
  GAMMA__N_EXCITED_STATE_9_REACTION = 59,
  GAMMA__N_EXCITED_STATE_10_REACTION = 60,
  GAMMA__N_EXCITED_STATE_11_REACTION = 61,
  GAMMA__N_EXCITED_STATE_12_REACTION = 62,
  GAMMA__N_EXCITED_STATE_13_REACTION = 63,
  GAMMA__N_EXCITED_STATE_14_REACTION = 64,
  GAMMA__N_EXCITED_STATE_15_REACTION = 65,
  GAMMA__N_EXCITED_STATE_16_REACTION = 66,
  GAMMA__N_EXCITED_STATE_17_REACTION = 67,
  GAMMA__N_EXCITED_STATE_18_REACTION = 68,
  GAMMA__N_EXCITED_STATE_19_REACTION = 69,
  GAMMA__N_EXCITED_STATE_20_REACTION = 70,
  GAMMA__N_EXCITED_STATE_21_REACTION = 71,
  GAMMA__N_EXCITED_STATE_22_REACTION = 72,
  GAMMA__N_EXCITED_STATE_23_REACTION = 73,
  GAMMA__N_EXCITED_STATE_24_REACTION = 74,
  GAMMA__N_EXCITED_STATE_25_REACTION = 75,
  GAMMA__N_EXCITED_STATE_26_REACTION = 76,
  GAMMA__N_EXCITED_STATE_27_REACTION = 77,
  GAMMA__N_EXCITED_STATE_28_REACTION = 78,
  GAMMA__N_EXCITED_STATE_29_REACTION = 79,
  GAMMA__N_EXCITED_STATE_30_REACTION = 80,
  GAMMA__N_EXCITED_STATE_31_REACTION = 81,
  GAMMA__N_EXCITED_STATE_32_REACTION = 82,
  GAMMA__N_EXCITED_STATE_33_REACTION = 83,
  GAMMA__N_EXCITED_STATE_34_REACTION = 84,
  GAMMA__N_EXCITED_STATE_35_REACTION = 85,
  GAMMA__N_EXCITED_STATE_36_REACTION = 86,
  GAMMA__N_EXCITED_STATE_37_REACTION = 87,
  GAMMA__N_EXCITED_STATE_38_REACTION = 88,
  GAMMA__N_EXCITED_STATE_39_REACTION = 89,
  GAMMA__N_EXCITED_STATE_40_REACTION = 90,
  GAMMA__N_CONTINUUM_REACTION = 91,
  GAMMA__CAPTURE_REACTION = 102,
  GAMMA__P_REACTION = 103,
  GAMMA__D_REACTION = 104,
  GAMMA__T_REACTION = 105,
  GAMMA__HE3_REACTION = 106,
  GAMMA__ALPHA_REACTION = 107,
  GAMMA__2ALPHA_REACTION = 108,
  GAMMA__3ALPHA_REACTION = 109,
  GAMMA__2P_REACTION = 111,
  GAMMA__P_ALPHA_REACTION = 112,
  GAMMA__T_2ALPHA_REACTION = 113,
  GAMMA__D_2ALPHA_REACTION = 114,
  GAMMA__P_D_REACTION = 115,
  GAMMA__P_T_REACTION = 116,
  GAMMA__D_ALPHA_REACTION = 117,
  GAMMA__5N_REACTION = 152,
  GAMMA__6N_REACTION = 153,
  GAMMA__2N_T_REACTION = 154,
  GAMMA__T_ALPHA_REACTION = 155,
  GAMMA__4N_P_REACTION = 156,
  GAMMA__3N_D_REACTION = 157,
  GAMMA__N_D_ALPHA_REACTION = 158,
  GAMMA__2N_P_ALPHA_REACTION = 159,
  GAMMA__7N_REACTION = 160,
  GAMMA__8N_REACTION = 161,
  GAMMA__5N_P_REACTION = 162,
  GAMMA__6N_P_REACTION = 163,
  GAMMA__7N_P_REACTION = 164,
  GAMMA__4N_ALPHA_REACTION = 165,
  GAMMA__5N_ALPHA_REACTION = 166,
  GAMMA__6N_ALPHA_REACTION = 167,
  GAMMA__7N_ALPHA_REACTION = 168,
  GAMMA__4N_D_REACTION = 169,
  GAMMA__5N_D_REACTION = 170,
  GAMMA__6N_D_REACTION = 171,
  GAMMA__3N_T_REACTION = 172,
  GAMMA__4N_T_REACTION = 173,
  GAMMA__5N_T_REACTION = 174,
  GAMMA__6N_T_REACTION = 175,
  GAMMA__2N_HE3_REACTION = 176,
  GAMMA__3N_HE3_REACTION = 177,
  GAMMA__4N_HE3_REACTION = 178,
  GAMMA__3N_2P_REACTION = 179,
  GAMMA__3N_2ALPHA_REACTION = 180,
  GAMMA__3N_P_ALPHA_REACTION = 181,
  GAMMA__D_T_REACTION = 182,
  GAMMA__N_P_D_REACTION = 183,
  GAMMA__N_P_T_REACTION = 184,
  GAMMA__N_D_T_REACTION = 185,
  GAMMA__N_P_HE3_REACTION = 186,
  GAMMA__N_D_HE3_REACTION = 187,
  GAMMA__N_T_HE3_REACTION = 188,
  GAMMA__N_T_ALPHA_REACTION = 189,
  GAMMA__2N_2P_REACTION = 190,
  GAMMA__P_HE3_REACTION = 191,
  GAMMA__D_HE3_REACTION = 192,
  GAMMA__HE3_ALPHA_REACTION = 193,
  GAMMA__4N_2P_REACTION = 194,
  GAMMA__4N_2ALPHA_REACTION = 195,
  GAMMA__4N_P_ALPHA_REACTION = 196,
  GAMMA__3P_REACTION = 197,
  GAMMA__N_3P_REACTION = 198,
  GAMMA__3N_2P_ALPHA_REACTION = 199,
  GAMMA__5N_2P_REACTION = 200,
  GAMMA__TOTAL_N_PRODUCTION = 201,
  GAMMA__TOTAL_GAMMA_PRODUCTION = 202,
  GAMMA__TOTAL_P_PRODUCTION = 203,
  GAMMA__TOTAL_D_PRODUCTION = 204,
  GAMMA__TOTAL_T_PRODUCTION = 205,
  GAMMA__TOTAL_HE3_PRODUCTION = 206,
  GAMMA__TOTAL_ALPHA_PRODUCTION = 207,
  GAMMA__AVERAGE_HEATING = 301,
  GAMMA__DAMAGE = 444,
  GAMMA__P_EXCITED_STATE_0_REACTION = 600,
  GAMMA__P_EXCITED_STATE_1_REACTION = 601,
  GAMMA__P_EXCITED_STATE_2_REACTION = 602,
  GAMMA__P_EXCITED_STATE_3_REACTION = 603,
  GAMMA__P_EXCITED_STATE_4_REACTION = 604,
  GAMMA__P_EXCITED_STATE_5_REACTION = 605,
  GAMMA__P_EXCITED_STATE_6_REACTION = 606,
  GAMMA__P_EXCITED_STATE_7_REACTION = 607,
  GAMMA__P_EXCITED_STATE_8_REACTION = 608,
  GAMMA__P_EXCITED_STATE_9_REACTION = 609,
  GAMMA__P_EXCITED_STATE_10_REACTION = 610,
  GAMMA__P_EXCITED_STATE_11_REACTION = 611,
  GAMMA__P_EXCITED_STATE_12_REACTION = 612,
  GAMMA__P_EXCITED_STATE_13_REACTION = 613,
  GAMMA__P_EXCITED_STATE_14_REACTION = 614,
  GAMMA__P_EXCITED_STATE_15_REACTION = 615,
  GAMMA__P_EXCITED_STATE_16_REACTION = 616,
  GAMMA__P_EXCITED_STATE_17_REACTION = 617,
  GAMMA__P_EXCITED_STATE_18_REACTION = 618,
  GAMMA__P_EXCITED_STATE_19_REACTION = 619,
  GAMMA__P_EXCITED_STATE_20_REACTION = 620,
  GAMMA__P_EXCITED_STATE_21_REACTION = 621,
  GAMMA__P_EXCITED_STATE_22_REACTION = 622,
  GAMMA__P_EXCITED_STATE_23_REACTION = 623,
  GAMMA__P_EXCITED_STATE_24_REACTION = 624,
  GAMMA__P_EXCITED_STATE_25_REACTION = 625,
  GAMMA__P_EXCITED_STATE_26_REACTION = 626,
  GAMMA__P_EXCITED_STATE_27_REACTION = 627,
  GAMMA__P_EXCITED_STATE_28_REACTION = 628,
  GAMMA__P_EXCITED_STATE_29_REACTION = 629,
  GAMMA__P_EXCITED_STATE_30_REACTION = 630,
  GAMMA__P_EXCITED_STATE_31_REACTION = 631,
  GAMMA__P_EXCITED_STATE_32_REACTION = 632,
  GAMMA__P_EXCITED_STATE_33_REACTION = 633,
  GAMMA__P_EXCITED_STATE_34_REACTION = 634,
  GAMMA__P_EXCITED_STATE_35_REACTION = 635,
  GAMMA__P_EXCITED_STATE_36_REACTION = 636,
  GAMMA__P_EXCITED_STATE_37_REACTION = 637,
  GAMMA__P_EXCITED_STATE_38_REACTION = 638,
  GAMMA__P_EXCITED_STATE_39_REACTION = 639,
  GAMMA__P_EXCITED_STATE_40_REACTION = 640,
  GAMMA__P_EXCITED_STATE_41_REACTION = 641,
  GAMMA__P_EXCITED_STATE_42_REACTION = 642,
  GAMMA__P_EXCITED_STATE_43_REACTION = 643,
  GAMMA__P_EXCITED_STATE_44_REACTION = 644,
  GAMMA__P_EXCITED_STATE_45_REACTION = 645,
  GAMMA__P_EXCITED_STATE_46_REACTION = 646,
  GAMMA__P_EXCITED_STATE_47_REACTION = 647,
  GAMMA__P_EXCITED_STATE_48_REACTION = 648,
  GAMMA__P_CONTINUUM_REACTION = 649,
  GAMMA__D_EXCITED_STATE_0_REACTION = 650,
  GAMMA__D_EXCITED_STATE_1_REACTION = 651,
  GAMMA__D_EXCITED_STATE_2_REACTION = 652,
  GAMMA__D_EXCITED_STATE_3_REACTION = 653,
  GAMMA__D_EXCITED_STATE_4_REACTION = 654,
  GAMMA__D_EXCITED_STATE_5_REACTION = 655,
  GAMMA__D_EXCITED_STATE_6_REACTION = 656,
  GAMMA__D_EXCITED_STATE_7_REACTION = 657,
  GAMMA__D_EXCITED_STATE_8_REACTION = 658,
  GAMMA__D_EXCITED_STATE_9_REACTION = 659,
  GAMMA__D_EXCITED_STATE_10_REACTION = 660,
  GAMMA__D_EXCITED_STATE_11_REACTION = 661,
  GAMMA__D_EXCITED_STATE_12_REACTION = 662,
  GAMMA__D_EXCITED_STATE_13_REACTION = 663,
  GAMMA__D_EXCITED_STATE_14_REACTION = 664,
  GAMMA__D_EXCITED_STATE_15_REACTION = 665,
  GAMMA__D_EXCITED_STATE_16_REACTION = 666,
  GAMMA__D_EXCITED_STATE_17_REACTION = 667,
  GAMMA__D_EXCITED_STATE_18_REACTION = 668,
  GAMMA__D_EXCITED_STATE_19_REACTION = 669,
  GAMMA__D_EXCITED_STATE_20_REACTION = 670,
  GAMMA__D_EXCITED_STATE_21_REACTION = 671,
  GAMMA__D_EXCITED_STATE_22_REACTION = 672,
  GAMMA__D_EXCITED_STATE_23_REACTION = 673,
  GAMMA__D_EXCITED_STATE_24_REACTION = 674,
  GAMMA__D_EXCITED_STATE_25_REACTION = 675,
  GAMMA__D_EXCITED_STATE_26_REACTION = 676,
  GAMMA__D_EXCITED_STATE_27_REACTION = 677,
  GAMMA__D_EXCITED_STATE_28_REACTION = 678,
  GAMMA__D_EXCITED_STATE_29_REACTION = 679,
  GAMMA__D_EXCITED_STATE_30_REACTION = 680,
  GAMMA__D_EXCITED_STATE_31_REACTION = 681,
  GAMMA__D_EXCITED_STATE_32_REACTION = 682,
  GAMMA__D_EXCITED_STATE_33_REACTION = 683,
  GAMMA__D_EXCITED_STATE_34_REACTION = 684,
  GAMMA__D_EXCITED_STATE_35_REACTION = 685,
  GAMMA__D_EXCITED_STATE_36_REACTION = 686,
  GAMMA__D_EXCITED_STATE_37_REACTION = 687,
  GAMMA__D_EXCITED_STATE_38_REACTION = 688,
  GAMMA__D_EXCITED_STATE_39_REACTION = 689,
  GAMMA__D_EXCITED_STATE_40_REACTION = 690,
  GAMMA__D_EXCITED_STATE_41_REACTION = 691,
  GAMMA__D_EXCITED_STATE_42_REACTION = 692,
  GAMMA__D_EXCITED_STATE_43_REACTION = 693,
  GAMMA__D_EXCITED_STATE_44_REACTION = 694,
  GAMMA__D_EXCITED_STATE_45_REACTION = 695,
  GAMMA__D_EXCITED_STATE_46_REACTION = 696,
  GAMMA__D_EXCITED_STATE_47_REACTION = 697,
  GAMMA__D_EXCITED_STATE_48_REACTION = 698,
  GAMMA__D_CONTINUUM_REACTION = 699,
  GAMMA__T_EXCITED_STATE_0_REACTION = 700,
  GAMMA__T_EXCITED_STATE_1_REACTION = 701,
  GAMMA__T_EXCITED_STATE_2_REACTION = 702,
  GAMMA__T_EXCITED_STATE_3_REACTION = 703,
  GAMMA__T_EXCITED_STATE_4_REACTION = 704,
  GAMMA__T_EXCITED_STATE_5_REACTION = 705,
  GAMMA__T_EXCITED_STATE_6_REACTION = 706,
  GAMMA__T_EXCITED_STATE_7_REACTION = 707,
  GAMMA__T_EXCITED_STATE_8_REACTION = 708,
  GAMMA__T_EXCITED_STATE_9_REACTION = 709,
  GAMMA__T_EXCITED_STATE_10_REACTION = 710,
  GAMMA__T_EXCITED_STATE_11_REACTION = 711,
  GAMMA__T_EXCITED_STATE_12_REACTION = 712,
  GAMMA__T_EXCITED_STATE_13_REACTION = 713,
  GAMMA__T_EXCITED_STATE_14_REACTION = 714,
  GAMMA__T_EXCITED_STATE_15_REACTION = 715,
  GAMMA__T_EXCITED_STATE_16_REACTION = 716,
  GAMMA__T_EXCITED_STATE_17_REACTION = 717,
  GAMMA__T_EXCITED_STATE_18_REACTION = 718,
  GAMMA__T_EXCITED_STATE_19_REACTION = 719,
  GAMMA__T_EXCITED_STATE_20_REACTION = 720,
  GAMMA__T_EXCITED_STATE_21_REACTION = 721,
  GAMMA__T_EXCITED_STATE_22_REACTION = 722,
  GAMMA__T_EXCITED_STATE_23_REACTION = 723,
  GAMMA__T_EXCITED_STATE_24_REACTION = 724,
  GAMMA__T_EXCITED_STATE_25_REACTION = 725,
  GAMMA__T_EXCITED_STATE_26_REACTION = 726,
  GAMMA__T_EXCITED_STATE_27_REACTION = 727,
  GAMMA__T_EXCITED_STATE_28_REACTION = 728,
  GAMMA__T_EXCITED_STATE_29_REACTION = 729,
  GAMMA__T_EXCITED_STATE_30_REACTION = 730,
  GAMMA__T_EXCITED_STATE_31_REACTION = 731,
  GAMMA__T_EXCITED_STATE_32_REACTION = 732,
  GAMMA__T_EXCITED_STATE_33_REACTION = 733,
  GAMMA__T_EXCITED_STATE_34_REACTION = 734,
  GAMMA__T_EXCITED_STATE_35_REACTION = 735,
  GAMMA__T_EXCITED_STATE_36_REACTION = 736,
  GAMMA__T_EXCITED_STATE_37_REACTION = 737,
  GAMMA__T_EXCITED_STATE_38_REACTION = 738,
  GAMMA__T_EXCITED_STATE_39_REACTION = 739,
  GAMMA__T_EXCITED_STATE_40_REACTION = 740,
  GAMMA__T_EXCITED_STATE_41_REACTION = 741,
  GAMMA__T_EXCITED_STATE_42_REACTION = 742,
  GAMMA__T_EXCITED_STATE_43_REACTION = 743,
  GAMMA__T_EXCITED_STATE_44_REACTION = 744,
  GAMMA__T_EXCITED_STATE_45_REACTION = 745,
  GAMMA__T_EXCITED_STATE_46_REACTION = 746,
  GAMMA__T_EXCITED_STATE_47_REACTION = 747,
  GAMMA__T_EXCITED_STATE_48_REACTION = 748,
  GAMMA__T_CONTINUUM_REACTION = 749,
  GAMMA__HE3_EXCITED_STATE_0_REACTION = 750,
  GAMMA__HE3_EXCITED_STATE_1_REACTION = 751,
  GAMMA__HE3_EXCITED_STATE_2_REACTION = 752,
  GAMMA__HE3_EXCITED_STATE_3_REACTION = 753,
  GAMMA__HE3_EXCITED_STATE_4_REACTION = 754,
  GAMMA__HE3_EXCITED_STATE_5_REACTION = 755,
  GAMMA__HE3_EXCITED_STATE_6_REACTION = 756,
  GAMMA__HE3_EXCITED_STATE_7_REACTION = 757,
  GAMMA__HE3_EXCITED_STATE_8_REACTION = 758,
  GAMMA__HE3_EXCITED_STATE_9_REACTION = 759,
  GAMMA__HE3_EXCITED_STATE_10_REACTION = 760,
  GAMMA__HE3_EXCITED_STATE_11_REACTION = 761,
  GAMMA__HE3_EXCITED_STATE_12_REACTION = 762,
  GAMMA__HE3_EXCITED_STATE_13_REACTION = 763,
  GAMMA__HE3_EXCITED_STATE_14_REACTION = 764,
  GAMMA__HE3_EXCITED_STATE_15_REACTION = 765,
  GAMMA__HE3_EXCITED_STATE_16_REACTION = 766,
  GAMMA__HE3_EXCITED_STATE_17_REACTION = 767,
  GAMMA__HE3_EXCITED_STATE_18_REACTION = 768,
  GAMMA__HE3_EXCITED_STATE_19_REACTION = 769,
  GAMMA__HE3_EXCITED_STATE_20_REACTION = 770,
  GAMMA__HE3_EXCITED_STATE_21_REACTION = 771,
  GAMMA__HE3_EXCITED_STATE_22_REACTION = 772,
  GAMMA__HE3_EXCITED_STATE_23_REACTION = 773,
  GAMMA__HE3_EXCITED_STATE_24_REACTION = 774,
  GAMMA__HE3_EXCITED_STATE_25_REACTION = 775,
  GAMMA__HE3_EXCITED_STATE_26_REACTION = 776,
  GAMMA__HE3_EXCITED_STATE_27_REACTION = 777,
  GAMMA__HE3_EXCITED_STATE_28_REACTION = 778,
  GAMMA__HE3_EXCITED_STATE_29_REACTION = 779,
  GAMMA__HE3_EXCITED_STATE_30_REACTION = 780,
  GAMMA__HE3_EXCITED_STATE_31_REACTION = 781,
  GAMMA__HE3_EXCITED_STATE_32_REACTION = 782,
  GAMMA__HE3_EXCITED_STATE_33_REACTION = 783,
  GAMMA__HE3_EXCITED_STATE_34_REACTION = 784,
  GAMMA__HE3_EXCITED_STATE_35_REACTION = 785,
  GAMMA__HE3_EXCITED_STATE_36_REACTION = 786,
  GAMMA__HE3_EXCITED_STATE_37_REACTION = 787,
  GAMMA__HE3_EXCITED_STATE_38_REACTION = 788,
  GAMMA__HE3_EXCITED_STATE_39_REACTION = 789,
  GAMMA__HE3_EXCITED_STATE_40_REACTION = 790,
  GAMMA__HE3_EXCITED_STATE_41_REACTION = 791,
  GAMMA__HE3_EXCITED_STATE_42_REACTION = 792,
  GAMMA__HE3_EXCITED_STATE_43_REACTION = 793,
  GAMMA__HE3_EXCITED_STATE_44_REACTION = 794,
  GAMMA__HE3_EXCITED_STATE_45_REACTION = 795,
  GAMMA__HE3_EXCITED_STATE_46_REACTION = 796,
  GAMMA__HE3_EXCITED_STATE_47_REACTION = 797,
  GAMMA__HE3_EXCITED_STATE_48_REACTION = 798,
  GAMMA__HE3_CONTINUUM_REACTION = 799,
  GAMMA__ALPHA_EXCITED_STATE_0_REACTION = 800,
  GAMMA__ALPHA_EXCITED_STATE_1_REACTION = 801,
  GAMMA__ALPHA_EXCITED_STATE_2_REACTION = 802,
  GAMMA__ALPHA_EXCITED_STATE_3_REACTION = 803,
  GAMMA__ALPHA_EXCITED_STATE_4_REACTION = 804,
  GAMMA__ALPHA_EXCITED_STATE_5_REACTION = 805,
  GAMMA__ALPHA_EXCITED_STATE_6_REACTION = 806,
  GAMMA__ALPHA_EXCITED_STATE_7_REACTION = 807,
  GAMMA__ALPHA_EXCITED_STATE_8_REACTION = 808,
  GAMMA__ALPHA_EXCITED_STATE_9_REACTION = 809,
  GAMMA__ALPHA_EXCITED_STATE_10_REACTION = 810,
  GAMMA__ALPHA_EXCITED_STATE_11_REACTION = 811,
  GAMMA__ALPHA_EXCITED_STATE_12_REACTION = 812,
  GAMMA__ALPHA_EXCITED_STATE_13_REACTION = 813,
  GAMMA__ALPHA_EXCITED_STATE_14_REACTION = 814,
  GAMMA__ALPHA_EXCITED_STATE_15_REACTION = 815,
  GAMMA__ALPHA_EXCITED_STATE_16_REACTION = 816,
  GAMMA__ALPHA_EXCITED_STATE_17_REACTION = 817,
  GAMMA__ALPHA_EXCITED_STATE_18_REACTION = 818,
  GAMMA__ALPHA_EXCITED_STATE_19_REACTION = 819,
  GAMMA__ALPHA_EXCITED_STATE_20_REACTION = 820,
  GAMMA__ALPHA_EXCITED_STATE_21_REACTION = 821,
  GAMMA__ALPHA_EXCITED_STATE_22_REACTION = 822,
  GAMMA__ALPHA_EXCITED_STATE_23_REACTION = 823,
  GAMMA__ALPHA_EXCITED_STATE_24_REACTION = 824,
  GAMMA__ALPHA_EXCITED_STATE_25_REACTION = 825,
  GAMMA__ALPHA_EXCITED_STATE_26_REACTION = 826,
  GAMMA__ALPHA_EXCITED_STATE_27_REACTION = 827,
  GAMMA__ALPHA_EXCITED_STATE_28_REACTION = 828,
  GAMMA__ALPHA_EXCITED_STATE_29_REACTION = 829,
  GAMMA__ALPHA_EXCITED_STATE_30_REACTION = 830,
  GAMMA__ALPHA_EXCITED_STATE_31_REACTION = 831,
  GAMMA__ALPHA_EXCITED_STATE_32_REACTION = 832,
  GAMMA__ALPHA_EXCITED_STATE_33_REACTION = 833,
  GAMMA__ALPHA_EXCITED_STATE_34_REACTION = 834,
  GAMMA__ALPHA_EXCITED_STATE_35_REACTION = 835,
  GAMMA__ALPHA_EXCITED_STATE_36_REACTION = 836,
  GAMMA__ALPHA_EXCITED_STATE_37_REACTION = 837,
  GAMMA__ALPHA_EXCITED_STATE_38_REACTION = 838,
  GAMMA__ALPHA_EXCITED_STATE_39_REACTION = 839,
  GAMMA__ALPHA_EXCITED_STATE_40_REACTION = 840,
  GAMMA__ALPHA_EXCITED_STATE_41_REACTION = 841,
  GAMMA__ALPHA_EXCITED_STATE_42_REACTION = 842,
  GAMMA__ALPHA_EXCITED_STATE_43_REACTION = 843,
  GAMMA__ALPHA_EXCITED_STATE_44_REACTION = 844,
  GAMMA__ALPHA_EXCITED_STATE_45_REACTION = 845,
  GAMMA__ALPHA_EXCITED_STATE_46_REACTION = 846,
  GAMMA__ALPHA_EXCITED_STATE_47_REACTION = 847,
  GAMMA__ALPHA_EXCITED_STATE_48_REACTION = 848,
  GAMMA__ALPHA_CONTINUUM_REACTION = 849,
  GAMMA__2N_EXCITED_STATE_0_REACTION = 875,
  GAMMA__2N_EXCITED_STATE_1_REACTION = 876,
  GAMMA__2N_EXCITED_STATE_2_REACTION = 877,
  GAMMA__2N_EXCITED_STATE_3_REACTION = 878,
  GAMMA__2N_EXCITED_STATE_4_REACTION = 879,
  GAMMA__2N_EXCITED_STATE_5_REACTION = 880,
  GAMMA__2N_EXCITED_STATE_6_REACTION = 881,
  GAMMA__2N_EXCITED_STATE_7_REACTION = 882,
  GAMMA__2N_EXCITED_STATE_8_REACTION = 883,
  GAMMA__2N_EXCITED_STATE_9_REACTION = 884,
  GAMMA__2N_EXCITED_STATE_10_REACTION = 885,
  GAMMA__2N_EXCITED_STATE_11_REACTION = 886,
  GAMMA__2N_EXCITED_STATE_12_REACTION = 887,
  GAMMA__2N_EXCITED_STATE_13_REACTION = 888,
  GAMMA__2N_EXCITED_STATE_14_REACTION = 889,
  GAMMA__2N_EXCITED_STATE_15_REACTION = 890,
  GAMMA__2N_CONTINUUM_REACTION = 891
};

//! Convert a raw MT number to a PhotonuclearReactionType
PhotonuclearReactionType convertMTNumberToPhotonuclearReactionType(
						     const unsigned reaction );

} // end MonteCarlo namespace

namespace Utility{

/*! \brief Specialization of Utility::ToStringTraits for
 * MonteCarlo::PhotonuclearReactionType
 * \ingroup to_string_traits
 */
template<>
struct ToStringTraits<MonteCarlo::PhotonuclearReactionType>
{
  //! Convert the MonteCarlo::PhotonuclearReactionType to a string
  static std::string toString( const MonteCarlo::PhotonuclearReactionType type );

  //! Place the MonteCarlo::PhotonuclearReactionType in a stream
  static void toStream( std::ostream& os, const MonteCarlo::PhotonuclearReactionType type );
};
  
} // end Utility namespace

namespace std{

//! Stream operator for printing PhotonuclearReactionType enums
inline std::ostream& operator<<( std::ostream& os,
				 const MonteCarlo::PhotonuclearReactionType reaction )
{
  os << Utility::toString( reaction );
  return os;
}

} // end std namespace

namespace boost{

namespace serialization{

//! Serialize the MonteCarlo::PhotonuclearReactionType enums
template<typename Archive>
void serialize( Archive& archive,
                MonteCarlo::PhotonuclearReactionType& type,
                const unsigned version )
{
  if( Archive::is_saving::value )
    archive & (unsigned)type;
  else
  {
    unsigned raw_type;
    
    archive & raw_type;

    type = MonteCarlo::convertMTNumberToPhotonuclearReactionType( raw_type );
  }
}
  
} // end serialization namespace
  
} // end boost namespace

namespace Utility{

/*! Specialization of Utility::IsHashable for MonteCarlo::PhotonuclearReactionType
 * \ingroup type_traits
 */
template<>
struct IsHashable<MonteCarlo::PhotonuclearReactionType> : public std::true_type
{ /* ... */ };

} // end Utility namespace

namespace std{

//! Specialization of std::hash for MonteCarlo::PhotonuclearReactionType
template<>
struct hash<MonteCarlo::PhotonuclearReactionType> : public hash<unsigned>
{ /* ... */ };

} // end std namespace

#endif // end MONTE_CARLO_PHOTONUCLEAR_REACTION_TYPE_HPP

//---------------------------------------------------------------------------//
// end MonteCarlo_PhotonuclearReactionType.hpp
//---------------------------------------------------------------------------//
